services:
  openconnect:
    image: ${VPSOCKS_IMAGE}
    command: connect.sh
    ports:
      - "1080:1080"
    env_file:
     - path: ./vpn.env
       required: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
      - /dev/vhost-net:/dev/vhost-net
    healthcheck:
      test: pgrep openconnect || exit 1
      interval: 5s
      timeout: 30s
      retries: 15
      start_period: 5s
  sockd:
    image: ${VPSOCKS_IMAGE}
    command: sockd
    network_mode: service:openconnect
    depends_on:
        openconnect: 
          condition: service_healthy